### ISSUE TITLE
Répertoire ouvert au public

### ISSUE THREAD

**Issue by Ckram** [etalab/etalab#20]
Bonjour est-ce normal que ce répertoire soit ouvert au public ? On peut accéder à certains formulaire qui ne devrait pas être accessible à mon avis.

**Comment by abulte** [comment]
Bonjour,

Oui, il est normal que ce dépôt soit ouvert au public. Quelque chose a toutefois pu nous échapper. A quels formulaires faites-vous référence ?

Merci !

**Comment by Ckram** [comment]
Typiquement https://raw.github.com/wiki/betagouv/beta.gouv.fr/files/formulaire.pdf

**Comment by abulte** [comment]
En l’occurrence l’envoi de ce formulaire n’est pas suffisant pour compléter la procédure. Nous préférons le laisser ici afin de le rendre facilement accessible aux nouveaux arrivés.

Merci pour votre vigilance !
