### ISSUE TITLE
Lien vers algos publics

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/etalab#27]
Hello @bzg,

Dans https://github.com/etalab/etalab/commit/a1de90eb532c1f973117a09df20d3a0054e5bf37 tu as supprimé la partie algos publics d'ici. C'est dans un répertoire https://github.com/etalab/algorithmes-publics maintenant.

Les algos publics sont mentionnés dans le README. Faut-il mettre à jour ceci ?

**Comment by bzg** [comment]
C'est corrigé, merci de m'avoir signalé l'erreur.
