### ISSUE TITLE
Idées d’articles à rajouter au livret de bienvenue

### ISSUE THREAD

**Issue by bboulesteix** [etalab/etalab#5]
Les articles qui suivent, une fois écrits, pourraient être rajoutés au dépôt GitHub ([etalab/etalab](https://github.com/etalab/etalab)) qui fait office de livret de bienvenue pour les nouveaux arrivants.

* [x] **Nos rituels** : pour faire la liste des grands rendez-vous organisés au sein d’Etalab.
* [x] **Les outils que nous utilisons** : pour faire la liste des outils avec lesquels nous travaillons et ainsi permettre aux nouveaux arrivants de tout installer dès leur première journée.
* [ ] **Organigramme** : pour comprendre qui fait quoi au sein d’Etalab.
* [x] **Qui contacter pour quoi** : une sorte d’annuaire pour rediriger les bonnes questions vers les bonnes personnes.
* [ ] **Avantages** : un article consacré aux avantages en matière de santé, de congés, de transport, et ainsi de suite, pour faire en sorte qu’aucun membre d’Etalab ne passe à côté de ce à quoi il a droit.
* [ ] **Comment nos projects fonctionnent** : pour expliquer le déroulement des projets.

**Comment by bzg** [comment]
J'ai créé une page ["activités"](https://github.com/etalab/etalab/blob/master/activites.md) proposant une synthèse des activités.  Ce n'est pas un organigramme et ça n'a pas forcément vocation à le devenir, mais je pense que ça peut être utile aux nouveaux arrivants.

**Comment by bzg** [comment]
Pour l'organigramme, c'est virtuellement dans https://www.etalab.gouv.fr/equipe

Pour les avantages, je vois l'idée mais je ne suis pas sûr que cela doivent figurer ici.

Pour le fonctionnement des projets, cela dépend des projets :)
