### ISSUE TITLE
Question typographique : pourquoi ne met-on jamais d’accent aigu sur le premier « E » du mot `etalab` ?

### ISSUE THREAD

**Issue by thom4parisot** [etalab/etalab#6]
Vu sur le Slack `#startup-datagouv`.

Ressources : 

- https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000023619063&categorieLien=id
- https://lannuaire.service-public.fr/gouvernement/administration-centrale-ou-ministere_436106

> Ce qui était considéré important à l'époque de la création d' _etalab_ était que ce ne soit pas un sigle, comme on les aime tant dans l'administration, mais plutôt un mot, comme une marque. Ce n'est donc pas ÉtatLab mais bien _etalab_ (si on respecte la graphie du logo, comme le recommande par exemple Wikipédia pour les marques) ou _Etalab_ (si on recapitalise pour suivre les conventions typographiques habituelles)
> 
> Je pratique _etalab_ aussi souvent que possible, mais en premier mot de phrase je repasse quand même à _Etalab_, sinon visuellement cela choque vraiment (sauf à la mettre dans une police ou couleur différente).

Question sous-jascente : « C’est une question récurrente qui mériterait d’être documentée mais où ? ».

**Comment by jdesboeufs** [comment]
Henri n’a pas créé Etalab.
Il en a pris la tête a posteriori.

**Comment by teleboas** [comment]
@jdesboeufs : très juste, formulation amendée
